name: client_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  chopper: ^4.0.4
  cupertino_icons: ^1.0.2
  extended_masked_text: ^2.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  mask_text_input_formatter: ^2.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  time_picker_widget: ^1.0.0+10
  url_launcher: ^6.0.18
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  chopper_generator: ^4.0.3
  dio: ^4.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_lints: ^1.0.0
  mockito: ^5.0.5
  rxdart: ^0.26.0

flutter:
  assets:
    - assets/
    - .env

  uses-material-design: true